=== rodgalan/SchibstedWebapp/FlowConfigBeans/resources/configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://webapp.test.schibsted.com/controller/flowconfig/beans"
	xmlns:tns="http://webapp.test.schibsted.com/controller/flowconfig/beans"
	elementFormDefault="qualified">

	<annotation>
		<appinfo>Schibsted Webapp MVC Flow Configuration</appinfo>
		<documentation xml:lang="en">
			Define flow, authentication and authorization for each user action:
				- Input path
				- Needs authorization or not
				- List of rols allowed (if needs authentication). Only processed if the action is under authorization requirement. 
				- Business Action is going to be executed
			[	- View Object is going to be generated by Business Action (if it's needed)  ]
				- Static or dynamic view is going to be showed to user as a result of his/her action   
		</documentation>
	</annotation>

	<complexType name="Forward">
		<attribute type="string" name="name" use="required" />
		<attribute type="string" name="path" use="required" />
		<attribute type="tns:ForwardType" name="type" use="required" />
	</complexType>

	<simpleType name="ForwardType" final="restriction">
		<restriction base="string">
			<enumeration value="static" />
			<enumeration value="dynamic" />
			<enumeration value="redirect" />
		</restriction>
	</simpleType>

	<complexType name="Role">
		<attribute type="string" name="name" use="required" />
	</complexType>

	<complexType name="AccesRoles">
		<sequence>
			<element name="role" type="tns:Role" maxOccurs="unbounded"
				minOccurs="0" />
		</sequence>
	</complexType>

	<complexType name="BusinessAction">
		<sequence>
			<element name="accesRoles" type="tns:AccesRoles" maxOccurs="1"
				minOccurs="0" />
			<element name="forward" type="tns:Forward" maxOccurs="unbounded"
				minOccurs="1" />
		</sequence>
		<attribute type="string" name="path" use="required" />
		<attribute type="string" name="businessActionClass" use="required" />
		<attribute type="boolean" name="authenticated" use="required" />
	</complexType>

	<element name="flowConfig">
		<complexType>
			<sequence>
				<element type="tns:BusinessAction" name="businessAction"
					maxOccurs="unbounded" minOccurs="1" />
			</sequence>
		</complexType>
	</element>

</schema>

=== rodgalan/SchibstedWebapp/SchibstedWebapp/src/main/resources/config/configuration.xml
<?xml version="1.0" encoding="UTF-8"?>

<tns:flowConfig
	xmlns:tns="http://webapp.test.schibsted.com/controller/flowconfig/beans"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://webapp.test.schibsted.com/controller/flowconfig/beans configuration.xsd ">

	<tns:businessAction authenticated="true" path="/page1" httpMethod="GET"
		businessActionClass="com.schibsted.test.webapp.businessAction.UserInfoAction" accesRole="page1">
		<tns:forward name="success" path="com.schibsted.test.webapp.view.Page1" type="dynamic" />
	</tns:businessAction>

	<tns:businessAction authenticated="true" path="/page2" httpMethod="GET"
		businessActionClass="com.schibsted.test.webapp.businessAction.UserInfoAction" accesRole="page2">
		<tns:forward name="success" path="com.schibsted.test.webapp.view.Page2" type="dynamic" />
	</tns:businessAction>

	<tns:businessAction authenticated="true" path="/page3" httpMethod="GET"
		businessActionClass="com.schibsted.test.webapp.businessAction.UserInfoAction" accesRole="page3">
		<tns:forward name="success" path="com.schibsted.test.webapp.view.Page3" type="dynamic" />
	</tns:businessAction>

	<tns:businessAction authenticated="false" path="/login" httpMethod="GET"
		businessActionClass="com.schibsted.test.webapp.businessAction.LoginAction">
		<!-- <tns:forward name="success" path="/login.html" type="static" /> -->
		<tns:forward name="success" path="com.schibsted.test.webapp.view.LoginView" type="dynamic" />
	</tns:businessAction>
	
	<!-- TODO: redirect path must be specified with /  static without !!-->
	<!-- ALWAYS REDIRECT AFTER A POST! -->
	<tns:businessAction authenticated="false" path="/validateUser" httpMethod="POST"
		businessActionClass="com.schibsted.test.webapp.businessAction.ValidateUserAction">
		<tns:forward name="success" path="/login" type="redirect" />    <!-- ALWAYS REDIRECT AFTER A POST! -->
		<tns:forward name="loginError" path="/login" type="redirect" />
	</tns:businessAction>
	
	<tns:businessAction authenticated="true" path="/closeUserSession" httpMethod="GET"
		businessActionClass="com.schibsted.test.webapp.businessAction.CloseUserAction">
		<tns:forward name="success" path="/login" type="redirect" /> 
		<!-- <tns:forward name="loginError" path="login" type="redirect" /> -->
	</tns:businessAction>

</tns:flowConfig>
